# Hyperparameters for the Word2Vec model
hyperparameters_grid:
  - min_count: 3
    epochs: 30
    vector_size: 48
    window: 10
    ns_exponent: 0.75
  - min_count: 5
    epochs: 30
    vector_size: 48
    window: 10
    ns_exponent: 0.75
  - min_count: 10
    epochs: 30
    vector_size: 48
    window: 10
    ns_exponent: 0.75

# Images: https://github.com/aws/deep-learning-containers/blob/master/available_images.md
sagemaker:
  image: "763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-inference:2.14.1-gpu-py310-cu118-ubuntu20.04-sagemaker"
  role: "SageMaker-MLOpsEngineer"
  instance: "ml.g4dn.xlarge"
